export enum AppTableTypes {
  SHOP_TABLE_TYPE = 1,
  COUNTER_PARTIES_TABLE_TYPE,
  MANUFACTURE_TABLE_TYPE,
  SHOP_TYPES_TABLE_TYPE,
  SHOP_DEPARTMENTS_TABLE_TYPE,
  SALES_CHANELS_TABLE_TYPE,
  SHOP_SPECIALIZATIONS_TABLE_TYPE,
  CONTRACTS_TABLE_TYPE
}
